// Generated by https://quicktype.io

export interface AllCards {
    items: Item[];
}

export interface Item {
    name:     string;
    id:       number;
    maxLevel: number;
    iconUrls: IconUrls;
}

export interface IconUrls {
    medium: string;
}

